#global config

global:
  scrape_interval:     15s 
  evaluation_interval: 5s
  scrape_timeout: 1m

# Alertmanager configuration

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Scrape configs only contain one scrape target

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['0.0.0.0:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9100
    relabel_configs:
      - target_label: 'instance'

